import React, { useState } from 'react';
import { MessageSquare, Send, Sparkles } from 'lucide-react';
import { useDatabase } from '../contexts/DatabaseContext';
import LoadingSpinner from './ui/LoadingSpinner';

interface QueryResult {
  query: string;
  explanation: string;
  timestamp: Date;
}

const AIChat: React.FC = () => {
  const dbContext = useDatabase();
  const selectedTable = dbContext?.selectedTable;
  const credentials = dbContext?.credentials;
  const tables = dbContext?.tables;
  const [question, setQuestion] = useState('');
  const [results, setResults] = useState<QueryResult[]>([]);
  const [isLoading, setIsLoading] = useState(false);

  // Helper to get schema for selected table
  const getSchemaForSelectedTable = () => {
    if (!selectedTable || !tables) return null;
    const table = tables.find(t => t.name === selectedTable);
    if (!table) return null;
    return {
      table_name: table.name,
      columns: table.columns || []
    };
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim() || !selectedTable) return;

    setIsLoading(true);
    const schemaInfo = getSchemaForSelectedTable();
    if (!schemaInfo) {
      setIsLoading(false);
      return;
    }

    try {
      const response = await fetch('http://localhost:5000/ai/generate-dml', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          user_request: question,
          schema_info: schemaInfo,
          db_type: "PostgreSQL"
        }),
      });
      const data = await response.json();
      if (data.dml) {
        setResults(prev => [{
          query: data.dml,
          explanation: "This is the SQL statement generated by Gemini for your request.",
          timestamp: new Date()
        }, ...prev]);
      } else {
        setResults(prev => [{
          query: "",
          explanation: data.error || "Failed to generate SQL.",
          timestamp: new Date()
        }, ...prev]);
      }
    } catch (error) {
      setResults(prev => [{
        query: "",
        explanation: "Error communicating with AI backend.",
        timestamp: new Date()
      }, ...prev]);
    }

    setQuestion('');
    setIsLoading(false);
  };

  return (
    <div className="bg-gray-800 rounded-lg h-full flex flex-col">
      <div className="p-4 border-b border-gray-700">
        <div className="flex items-center space-x-2">
          <MessageSquare className="h-5 w-5 text-blue-400" />
          <h3 className="font-medium text-white">AI Assistant</h3>
        </div>
        <p className="text-sm text-gray-400 mt-1">
          Ask questions about your data in natural language
        </p>
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {results.length === 0 ? (
          <div className="text-center text-gray-400 py-8">
            <Sparkles className="h-8 w-8 mx-auto mb-2 opacity-50" />
            <p className="text-sm">Ask me anything about your data!</p>
            <p className="text-xs mt-1">
              Try: "How many users signed up last week?" or "Show me the top 5 customers by revenue"
            </p>
          </div>
        ) : (
          results.map((result, index) => (
            <div key={index} className="space-y-3">
              <div className="bg-gray-700 rounded-lg p-3">
                <p className="text-white text-sm font-medium mb-2">Generated Query:</p>
                <code className="text-blue-300 text-xs bg-gray-900 p-2 rounded block overflow-x-auto">
                  {result.query}
                </code>
              </div>
              
              <div className="bg-gray-700 rounded-lg p-3">
                <p className="text-white text-sm font-medium mb-2">Explanation:</p>
                <p className="text-gray-300 text-sm">{result.explanation}</p>
              </div>

              <div className="text-xs text-gray-500 text-right">
                {result.timestamp.toLocaleTimeString()}
              </div>
            </div>
          ))
        )}
      </div>

      <form onSubmit={handleSubmit} className="p-4 border-t border-gray-700">
        <div className="flex space-x-2">
          <input
            type="text"
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask a question about your data..."
            className="flex-1 px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            disabled={isLoading}
          />
          <button
            type="submit"
            disabled={isLoading || !question.trim()}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? (
              <LoadingSpinner size="sm" />
            ) : (
              <Send className="h-4 w-4" />
            )}
          </button>
        </div>
      </form>
    </div>
  );
};

export default AIChat;